### ISSUE TITLE
Schedule - "Sendung verpasst"

### ISSUE THREAD

**Issue by luchmhor** [s0faking/plugin.video.orfon#10]
Maybe the transition to orfon rendered me blind. But I am missing the Menu item where you can browse the shows by date. Is it possible to get this back?

Thanks for your effort. Especially when using Firefix on.orf.at is almost not usable compared to tvthek and especially this kodi addon.

**Comment by s0faking** [comment]
It's the third Item from the top. (Schedule or Sendung verpasst). With ORF On you can browse a lot more dates, some shows even half a year back

**Comment by andyblaha** [comment]
Hi, I appreciate your effort, using your TVthek addon for years. Recently it is not possible for me to stream news features like ZIB1 or Wien Heute anymore, error message is "no stream available, unable to find a stream for this content" and sometimes also a popup window with OK button to confirm with the message "Wiedergabe nicht möglich. Für mehr Informationen Protokoll einsehen" (now, I am not so much techie as I'd like to be so how to find the logs to investigate?). Could the problem possibly be related to their chapter structure? The streams work somehow when I stream them in the browser (Firefox), but with great delays between chapters. Any ideas why this would happen? 
![grafik](https://github.com/s0faking/plugin.video.orfon/assets/151776878/39e170ac-7780-40e8-9683-c429ba98db7a)

**Comment by s0faking** [comment]
The most recent patches are already merged into the original tvthek addon and the addon has been renamed. Try to Install/Update the ORF tvthek (now ORF On) addon from the official KODi repo and uninstall the plugin.video.orfon addon

This is probably related to issue #6

Hope this helps

**Comment by andyblaha** [comment]
many thanks, I tried, and after reinstalling the "new" tvthek addon twice, it started to work. I am missing the "play all" feature though when "view chapters" is enabled. thanks for your advise,
all the best
Andy

**Comment by s0faking** [comment]
> many thanks, I tried, and after reinstalling the "new" tvthek addon twice, it started to work. I am missing the "play all" feature though when "view chapters" is enabled. thanks for your advise,
> all the best
> Andy

Hey Andy

Checkout #5. The Play All listitem has been removed because of the builtin "Play from here" option which you can find in the context menu

**Comment by andyblaha** [comment]
perfect, many thanks!
