### ISSUE TITLE
New chapter system  less user friendly compared to old version (ORF TVThek)?

### ISSUE THREAD

**Issue by Autodrom** [s0faking/plugin.video.orfon#2]
Hello,

first of all - thanks for your effort! My family is using your app for years, they were quite upset when they realised that the older app has stopped working today. Is there a way to donate? 😊

My question is - why does the new version of not offer chapters any more? For example "Bundesland Heute", if you opened it the complete series is started instead of the chapter window like in the past? Did I miss something maybe? This was a big advantage as one was able to select the chapters - and not needed to see the whole thing.

**EDIT:** Sorry, I have to correct or precise. **The chapters are there**, if you click on the left in options and select "Zur Wiedergabeliste". But the old design was in comparison much more convenient, as you simply hit "OK" (or "ENTER" on Keyboard), and you had all chapters with on single hit. Now with this "go left", go downwards and "select clicks" it is much more work to "scroll" through the program. 
EDIT2: Okay, I have now read the posting that the latest update on Github of the old app (ORF TVThek) fixes the latest issue, and it is working again. THANKS!!!

Nevertheless: I would really appreciate if the "old" version design (in terms of chapters and its usage) could be reused in ORF ON as well. That would be great for the future, if ORF TVThek App is closing some time in future. 💯 

Thanks a lot for your effort!!!!
Autodrom

**Comment by s0faking** [comment]
Hi Autodrom,

> Hello,
> 
> first of all - thanks for your effort! My family is using your app for years, they were quite upset when they realised that the older app has stopped working today. Is there a way to donate? 😊

thx. glad you like the addon :) no need to donate. i do this 100% for fun, the challenge and to contribute to a software i've been using for almost 20 years now :)

> 
> My question is - why does the new version of not offer chapters any more? For example "Bundesland Heute", if you opened it the complete series is started instead of the chapter window like in the past? Did I miss something maybe? This was a big advantage as one was able to select the chapters - and not needed to see the whole thing.
> 
> **EDIT:** Sorry, I have to correct or precise. **The chapters are there**, if you click on the left in options and select "Zur Wiedergabeliste". But the old design was in comparison much more convenient, as you simply hit "OK" (or "ENTER" on Keyboard), and you had all chapters with on single hit. Now with this "go left", go downwards and "select clicks" it is much more work to "scroll" through the program. EDIT2: Okay, I have now read the posting that the latest update on Github of the old app (ORF TVThek) fixes the latest issue, and it is working again. THANKS!!!

you can actually change the chapters on the osd of the player if you click on the left playlist button 
![Screenshot 2024-05-22 230013](https://github.com/s0faking/plugin.video.orfon/assets/3915825/1bde7f18-8f03-4be0-8b73-61fac4a12853)


> 
> Nevertheless: I would really appreciate if the "old" version design (in terms of chapters and its usage) could be reused in ORF ON as well. That would be great for the future, if ORF TVThek App is closing some time in future. 💯

sure i will add a "back to the oldschool" (workprint title ;)) option to make that happen ;). reason for this change is that i had quite some feedback in the past about this where users wanted the stream to start immediately :) shouldn't be a big thing tough. 

> 
> Thanks a lot for your effort!!!! Autodrom

**Comment by wasinix** [comment]
Hey @s0faking, I just wanted to echo the praise from Autodrom.
Our household is also a long-time user of the old tvthek addon and is very grateful for your Orf.on adaptation.
I was also looking for a "buy me a beer" link or button here, but since you'd rather not receive donations, here's just a big "**THANK YOU**" for your work and contribution!
