### ISSUE TITLE
routing library - script.module.routing

### ISSUE THREAD

**Issue by cmikovits** [s0faking/plugin.video.orfon#4]
Is there a recommended way on how to install the needed script.module.routing pluging? I only found sources for a ca. 5 year old zip with this name.

thx.

**Comment by s0faking** [comment]
The addon is listed in the requirements and should be installed when adding the addon using the ZIP Install method. Which KODi Version are you using? No manual install of the Routing addon should be required

**Comment by s0faking** [comment]
https://kodi.wiki/view/Add-on:Plugin_routing

**Comment by Airbusflieger** [comment]
I run into the same problem when I installed the plugin on a current OSMC_TGT_rbp2_20240424 image. Adding a version tag

<import addon="script.module.routing" version="0.2.3"/>

in addon.xml worked for me.

**Comment by Airbusflieger** [comment]
Sorry, forgot to quote the xml.

`<import addon="script.module.routing" version="0.2.3"/>`

**Comment by s0faking** [comment]
should be fixed with the last commit
