### ISSUE TITLE
Alle Kapitel abspielen

### ISSUE THREAD

**Issue by killerbees19** [s0faking/plugin.video.orfon#5]
Danke für #2, das hat in meiner Verwandtschaft einigen sehr gefehlt. 😍

Was mir persönlich noch fehlt, dann ist dieses Addon ein perfekter Ersatz: "Alle Kapitel abspielen" wieder als oberster Eintrag, falls das möglich wäre. Gerne nur auf expliziten Wunsch mit einer Konfigurationsoption, wenn es andere User sonst stören könnte. 😶‍🌫️

**Comment by negesti** [comment]
Das ist doch genau das, was passiert wenn man eine Sendung auswählt?

**Comment by killerbees19** [comment]
> Das ist doch genau das, was passiert wenn man eine Sendung auswählt?

Aber nicht, wenn man die neue Option "Kapitel anzeigen" aktiviert. Dann werden die Kapitel zwar wie beim alten Addon als Liste angezeigt, aber es gibt keine Möglichkeit mehr, sie alle gleichzeitig zur Queue hinzuzufügen und bequem zu überspringen.

Oder übersehe ich eine offensichtliche Möglichkeit? :-)

**Comment by xmeadow** [comment]
Ohne noch daheim nachgeschaut zu haben: Normalerweise gibt es bei Kodi eine Option "Ab hier abspielen".

**Comment by killerbees19** [comment]
> Normalerweise gibt es bei Kodi eine Option "Ab hier abspielen".

Danke, wieder was gelernt. 😶

Mein Feature-Request hat sich somit erledigt 🙃
